### ISSUE TITLE
[Bug]: Cannot remove or delete a file included in the CMSIS tab

### ISSUE THREAD

**Issue by DBizz22** [Open-CMSIS-Pack/cmsis-toolbox#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can add a new file or existing file to the different source group folders in the CMSIS tab but no option to remove files from the group. If the file is removed or deleted using the file explorer, it persists in the tab.

### Expected Behavior

Need an option to remove and rename files from source groups using CMSIS tab options.

### Affected tools

- [ ] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [X] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [X] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
This sounds like a problem you are having when using the Arm CMSIS Solution extension within VSCode. If that is the case, please report your problem here: https://github.com/ARM-software/vscode-cmsis-csolution
This repository is for the CMSIS-Toolbox  command line tools being e.g. used as back-end by the extension or in CI flows.

**Comment by DBizz22** [comment]
Thanks
