### ISSUE TITLE
[Bug]: compile_commands.json is not copied into the `out` folder structure as specified by the file ".clangd" if the folder does not exist (edited)

### ISSUE THREAD

**Issue by FerdinandEn** [Open-CMSIS-Pack/cmsis-toolbox#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the current version, the file `compile_commands.json` is generated in the path `tmp\1` and no longer in the path `out`. However, the generated file .clangd still refers to the path `out\...`.

### Expected Behavior

Path in `.clangd `points to the directory with the file` compile_commands.json`

### Affected tools

- [X] cbuild
- [ ] cbuild-gen
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

### Environment

Win 11
CMSIS-Toolbox 2.5.0
CMSIS-Solution-Toolbox 1.38.0

**Comment by brondani** [comment]
In the latest cbuild version 2.5.0 as well as in previous versions, the file `compile_commands.json` is never copied automatically into the `out` folder. The copy happens only after running the `database` target:
```
cbuild <*.csolution.yml> -t <context>-database
```
Or by calling the `setup` command (recommended):
```
cbuild setup <*.csolution.yml> --context-set
```
Details of the setup mode:
https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/build-operation.md#details-of-the-setup-mode

**Comment by jkrech** [comment]
The VSCode Extension: Arm CMSIS Solution v1.38.0 does invoke `cbuild setup` in the "CMSIS Build Manager". Could you please check whether there is any error message present in the corresponding `output` tab of the panel which may have prevented the successful build.

**Comment by FerdinandEn** [comment]
@jkrech 
I cannot recognize any error message. The `.clangd` file is created automatically. As a test, I deleted the `tmp `and `out `directories as well as the `.clangd file`. Then I closed VSCode and restarted it. The` .clangd` file is created. The path generated here points to the `out `directory. 

When recompiling, `out `and `tmp `are created again. The file` compile_commands.json` is located in the directory` tmp\1`. To be able to use clangd, you have to adjust the path in `.clangd` manually. The last time I tested a little more intensively, the compile_`commands.json` file was created in `out`. A manual change of `.clangd` was not necessary.

**Comment by brondani** [comment]
@FerdinandEn It looks like the `compile_commands.json` file cannot be copied into the `out` folder structure if the directories do not exist.
Can you please confirm that, for example by running a normal build, which will properly create the `out` folder structure, and then running `cbuild setup`?
A fix for this issue is being provided in https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/162

**Comment by FerdinandEn** [comment]
@brondani I use the Keil Studio Pack in VSCode. I have selected CMSIS and then executed rebuild. The file `compile_commands.json` is located in `tmp\1`. After executing the instruction 

`` cbuild` setup <*.csolution.yml> --context-set``

the file `compile_commands.json` appears under `out\project\target`. The `tmp\1` directory still exists.

**Comment by FerdinandEn** [comment]
The used rebuild command is
````cbuild d:\uni\VScodeTest\01-GPIO1\GPIOmovLight.csolution.yml --rebuild --context-set --update-rte --packs --context GPIOmovLight+stLink````

If I delete `tmp\1`the build command fails. 

````cbuild d:\uni\VScodeTest\01-GPIO1\GPIOmovLight.csolution.yml --context-set --update-rte --packs --context GPIOmovLight+stLink````

I had to do an rebuild.

**Comment by brondani** [comment]
@FerdinandEn Thanks for testing it.
The fix was merged and will be part of the next CMSIS-Toolbox release TBD.

This is the effect in the background once the change will be applied:
![image](https://github.com/user-attachments/assets/2b520dd1-1f5c-4047-9d1a-b1cf6ea98b62)

Please note the purpose of the `tmp` directory, as its name suggests, is to store temporary files that are mostly used by CMake configuration and dependency tracking as well as object files. It should not be changed manually otherwise it may need a rebuild.

**Comment by jkrech** [comment]
Note that the `.clangd` is managed by the VSCode CMSIS Solution extension and not by the CMSIS-Toolbox.

I have raised this issue https://github.com/ARM-software/vscode-cmsis-csolution/issues/74 against the extension.
