### ISSUE TITLE
[Bug]: Malloc() cannot be used normally

### ISSUE THREAD

**Issue by flair0626** [Open-CMSIS-Pack/cmsis-toolbox#209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Enter the HardFault-Handler interrupt

### Steps To Reproduce

main.c
#include "RTE_Components.h"
#include CMSIS_device_header

#include <stdlib.h>

int main()
{
    uint8_t *p = (uint8_t *)malloc(100);
    for (;;)
    {
        p[0]++;
    }
}

cbuild.yml:
  misc:
    ASM:
      - -masm=auto
    C:
      - -std=gnu11
      - -Wno-macro-redefined
      - -Wno-pragma-pack
      - -Wno-parentheses-equality
      - -Wno-license-management
    CPP:
      - -Wno-macro-redefined
      - -Wno-pragma-pack
      - -Wno-parentheses-equality
      - -Wno-license-management
    Link:
      - --entry=Reset_Handler
      - --map
      - --info summarysizes
      - --summary_stderr
      - --diag_suppress=L6314W

### Affected tools

- [ ] cbuild
- [ ] cbuild2cmake
- [ ] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
@flair0626, would you be able to provide more information about your project. In the best case you simply provide the CMSIS Solution project with all files that you have been using and the command line you have been using to build the project. What is the build output messages that you are seeing? What does "normal use" mean to you?

**Comment by ReinhardKeil** [comment]
@flair0626 what GCC version and library are you using? Is it a distribution from Arm or a different installation?

**Comment by flair0626** [comment]
> @flair0626 what GCC version and library are you using? Is it a distribution from Arm or a different installation?
The same chip can be used normally with malloc() in KEIL MDK5, but using the same code in VS code MDK6 will result in errors. The AC6 compiler is also used in MDK6.

**Comment by ReinhardKeil** [comment]
Sorry, I missed that you are using AC6.  Did you check the HEAP setting in your project?

Could you provide a test project (ZIP file); you can attach it to that case.

**Comment by flair0626** [comment]
[Blank_solution.zip](https://github.com/user-attachments/files/17826500/Blank_solution.zip)
@ReinhardKeil

**Comment by chentang16** [comment]
I have looked into your attached project. 
In your startup_n32g031.s you used the legacy function __user_initial_stackheap to set up your stack and heap. Meanwhile, in VS Code by default it uses the standard linker script template together with device specific regions*.h file to preprocess into a scatter file to be used with AC6 or other compiler toolchain. Inside this linker script template you can see the stack and heap are defined there too. Your both stack and heap configuration in this way leads to a conflict, which you can see from the generated map file.
![2024-11-20_08-39-11](https://github.com/user-attachments/assets/130765dd-d036-41d0-903a-34707d933b64)

On the other hand, in µVision I suppose you are using the µVision auto-generated scatter file or your own customized scatter file, which may not contain extra stack and heap setup.

This manual page describes three ways to configure stack and heap: https://developer.arm.com/documentation/100073/0623/The-Arm-C-and-C---Libraries/Stack-and-heap-memory-allocation-and-the-Arm-C-and-C---libraries/Stack-pointer-initialization-and-heap-bounds?lang=en
namely 
"If you are using the C library's initialization code, use any of the following methods to configure the stack and heap:
- Use the symbols __initial_sp, __heap_base, and __heap_limit.
- Use a scatter file to define ARM_LIB_STACKHEAP, ARM_LIB_STACK, or ARM_LIB_HEAP regions.
- Implement __user_setup_stackheap() or __user_initial_stackheap()."
Please note that you have to choose **one** of these three ways, instead of using two of them at the same time.

**Comment by ReinhardKeil** [comment]
In case that you are creating a Device Family Pack consider using a C startup code as described here https://arm-software.github.io/CMSIS_6/latest/Core/startup_c_pg.html

This is generic and works across all toolchains.

**Comment by flair0626** [comment]
@ReinhardKeil   @chentang16 The problem has been solved, thank you very much!

**Comment by ReinhardKeil** [comment]
Reopen as I will add something to the documentation.

**Comment by ReinhardKeil** [comment]
Now covered under https://github.com/Open-CMSIS-Pack/cmsis-toolbox/blob/main/docs/CreateApplications.md#troubleshooting
